<?php

namespace Database\Seeders;

use App\Models\ClimateZoneMetadata;
use Illuminate\Database\Seeder;

class ClimateZoneMetadataSeeder extends Seeder
{
    public function run(): void
    {
        $zones = [
            [
                'name'               => 'Highland Equatorial',
                'slug'               => 'highland-equatorial',
                'description'        => 'High-altitude equatorial belt with consistent rainfall and cool temperatures. Ideal for specialty Arabica production.',
                'altitude_min'       => 1600,
                'altitude_max'       => 2200,
                'rainfall_range'     => '1,400–2,000 mm',
                'temperature_range'  => '14–22 °C',
                'humidity_range'     => '65–80 %',
                'coffee_suitability' => 'High',
                'is_active'          => true,
                'sort_order'         => 1,
            ],
            [
                'name'               => 'Mid-Altitude Tropical',
                'slug'               => 'mid-altitude-tropical',
                'description'        => 'Moderate altitude with warm days and cool nights. Suitable for both Arabica and Robusta varieties.',
                'altitude_min'       => 1000,
                'altitude_max'       => 1599,
                'rainfall_range'     => '1,200–1,600 mm',
                'temperature_range'  => '18–26 °C',
                'humidity_range'     => '60–75 %',
                'coffee_suitability' => 'Medium',
                'is_active'          => true,
                'sort_order'         => 2,
            ],
            [
                'name'               => 'Lowland Tropical',
                'slug'               => 'lowland-tropical',
                'description'        => 'Low-altitude tropical zone with high humidity and warm temperatures. Best suited for Robusta production.',
                'altitude_min'       => 200,
                'altitude_max'       => 999,
                'rainfall_range'     => '1,000–1,400 mm',
                'temperature_range'  => '22–32 °C',
                'humidity_range'     => '70–85 %',
                'coffee_suitability' => 'Medium',
                'is_active'          => true,
                'sort_order'         => 3,
            ],
            [
                'name'               => 'Volcanic Highland',
                'slug'               => 'volcanic-highland',
                'description'        => 'Volcanic soil highland zone with mineral-rich earth and high rainfall. Produces complex specialty coffee profiles.',
                'altitude_min'       => 1800,
                'altitude_max'       => 2400,
                'rainfall_range'     => '1,600–2,200 mm',
                'temperature_range'  => '12–20 °C',
                'humidity_range'     => '68–82 %',
                'coffee_suitability' => 'High',
                'is_active'          => true,
                'sort_order'         => 4,
            ],
            [
                'name'               => 'Semi-Arid Transitional',
                'slug'               => 'semi-arid-transitional',
                'description'        => 'Transitional zone between highland and lowland with irregular rainfall. Limited but possible coffee production.',
                'altitude_min'       => 500,
                'altitude_max'       => 1200,
                'rainfall_range'     => '700–1,100 mm',
                'temperature_range'  => '20–30 °C',
                'humidity_range'     => '45–60 %',
                'coffee_suitability' => 'Low',
                'is_active'          => true,
                'sort_order'         => 5,
            ],
            [
                'name'               => 'Tropical Rainforest',
                'slug'               => 'tropical-rainforest',
                'description'        => 'Köppen Af — hot and wet year-round with no distinct dry season. Common at low elevations near the equator.',
                'altitude_min'       => 0,
                'altitude_max'       => 800,
                'rainfall_range'     => '2,000–4,000 mm',
                'temperature_range'  => '24–28 °C',
                'humidity_range'     => '80–90 %',
                'coffee_suitability' => 'Medium',
                'is_active'          => true,
                'sort_order'         => 6,
            ],
            [
                'name'               => 'Tropical Monsoon',
                'slug'               => 'tropical-monsoon',
                'description'        => 'Köppen Am — a short dry season offset by very heavy monsoonal rainfall the rest of the year.',
                'altitude_min'       => 0,
                'altitude_max'       => 1000,
                'rainfall_range'     => '1,800–3,000 mm',
                'temperature_range'  => '24–30 °C',
                'humidity_range'     => '75–88 %',
                'coffee_suitability' => 'Medium',
                'is_active'          => true,
                'sort_order'         => 7,
            ],
            [
                'name'               => 'Tropical Savanna',
                'slug'               => 'tropical-savanna',
                'description'        => 'Köppen Aw — pronounced wet and dry seasons with warm temperatures throughout the year.',
                'altitude_min'       => 0,
                'altitude_max'       => 1200,
                'rainfall_range'     => '800–1,500 mm',
                'temperature_range'  => '22–32 °C',
                'humidity_range'     => '55–75 %',
                'coffee_suitability' => 'Medium',
                'is_active'          => true,
                'sort_order'         => 8,
            ],
            [
                'name'               => 'Hot Desert',
                'slug'               => 'hot-desert',
                'description'        => 'Köppen BWh — very low rainfall with extreme daytime heat, typical of subtropical deserts.',
                'altitude_min'       => null,
                'altitude_max'       => null,
                'rainfall_range'     => '<250 mm',
                'temperature_range'  => '25–40 °C',
                'humidity_range'     => '10–30 %',
                'coffee_suitability' => 'Low',
                'is_active'          => true,
                'sort_order'         => 9,
            ],
            [
                'name'               => 'Cold Desert',
                'slug'               => 'cold-desert',
                'description'        => 'Köppen BWk — arid interior/mid-latitude desert with wide seasonal temperature swings.',
                'altitude_min'       => null,
                'altitude_max'       => null,
                'rainfall_range'     => '<250 mm',
                'temperature_range'  => '−5–25 °C',
                'humidity_range'     => '15–35 %',
                'coffee_suitability' => 'Low',
                'is_active'          => true,
                'sort_order'         => 10,
            ],
            [
                'name'               => 'Hot Semi-Arid Steppe',
                'slug'               => 'hot-semi-arid-steppe',
                'description'        => 'Köppen BSh — transitional dry grassland climate warmer and slightly wetter than true desert.',
                'altitude_min'       => null,
                'altitude_max'       => null,
                'rainfall_range'     => '250–500 mm',
                'temperature_range'  => '20–35 °C',
                'humidity_range'     => '20–40 %',
                'coffee_suitability' => 'Low',
                'is_active'          => true,
                'sort_order'         => 11,
            ],
            [
                'name'               => 'Cold Semi-Arid Steppe',
                'slug'               => 'cold-semi-arid-steppe',
                'description'        => 'Köppen BSk — dry grassland climate with cold winters, common on continental interiors.',
                'altitude_min'       => null,
                'altitude_max'       => null,
                'rainfall_range'     => '250–500 mm',
                'temperature_range'  => '−10–25 °C',
                'humidity_range'     => '25–45 %',
                'coffee_suitability' => 'Low',
                'is_active'          => true,
                'sort_order'         => 12,
            ],
            [
                'name'               => 'Mediterranean',
                'slug'               => 'mediterranean',
                'description'        => 'Köppen Csa/Csb — hot, dry summers and mild, wet winters.',
                'altitude_min'       => null,
                'altitude_max'       => null,
                'rainfall_range'     => '400–900 mm',
                'temperature_range'  => '10–30 °C',
                'humidity_range'     => '45–65 %',
                'coffee_suitability' => 'Low',
                'is_active'          => true,
                'sort_order'         => 13,
            ],
            [
                'name'               => 'Humid Subtropical',
                'slug'               => 'humid-subtropical',
                'description'        => 'Köppen Cfa — hot, humid summers and mild winters with rainfall spread through the year.',
                'altitude_min'       => null,
                'altitude_max'       => null,
                'rainfall_range'     => '1,000–1,600 mm',
                'temperature_range'  => '5–28 °C',
                'humidity_range'     => '55–75 %',
                'coffee_suitability' => 'Medium',
                'is_active'          => true,
                'sort_order'         => 14,
            ],
            [
                'name'               => 'Oceanic',
                'slug'               => 'oceanic',
                'description'        => 'Köppen Cfb — mild, narrow temperature range year-round with consistent rainfall, moderated by coastal/maritime influence.',
                'altitude_min'       => null,
                'altitude_max'       => null,
                'rainfall_range'     => '800–1,400 mm',
                'temperature_range'  => '5–20 °C',
                'humidity_range'     => '65–85 %',
                'coffee_suitability' => 'Low',
                'is_active'          => true,
                'sort_order'         => 15,
            ],
            [
                'name'               => 'Humid Continental',
                'slug'               => 'humid-continental',
                'description'        => 'Köppen Dfa/Dfb — hot to warm summers and cold, snowy winters found across large continental interiors.',
                'altitude_min'       => null,
                'altitude_max'       => null,
                'rainfall_range'     => '600–1,200 mm',
                'temperature_range'  => '−15–25 °C',
                'humidity_range'     => '55–75 %',
                'coffee_suitability' => 'Low',
                'is_active'          => true,
                'sort_order'         => 16,
            ],
            [
                'name'               => 'Subarctic',
                'slug'               => 'subarctic',
                'description'        => 'Köppen Dfc — very cold, long winters with short, cool summers.',
                'altitude_min'       => null,
                'altitude_max'       => null,
                'rainfall_range'     => '300–600 mm',
                'temperature_range'  => '−30–18 °C',
                'humidity_range'     => '60–80 %',
                'coffee_suitability' => 'Low',
                'is_active'          => true,
                'sort_order'         => 17,
            ],
            [
                'name'               => 'Tundra',
                'slug'               => 'tundra',
                'description'        => 'Köppen ET — treeless climate with short, cool summers and long, frigid winters.',
                'altitude_min'       => null,
                'altitude_max'       => null,
                'rainfall_range'     => '150–350 mm',
                'temperature_range'  => '−25–10 °C',
                'humidity_range'     => '60–85 %',
                'coffee_suitability' => 'Low',
                'is_active'          => true,
                'sort_order'         => 18,
            ],
            [
                'name'               => 'Ice Cap',
                'slug'               => 'ice-cap',
                'description'        => 'Köppen EF — permanently below freezing, found at the poles and highest mountain elevations.',
                'altitude_min'       => null,
                'altitude_max'       => null,
                'rainfall_range'     => '<200 mm',
                'temperature_range'  => '−40–−5 °C',
                'humidity_range'     => '50–70 %',
                'coffee_suitability' => 'Low',
                'is_active'          => true,
                'sort_order'         => 19,
            ],
        ];

        foreach ($zones as $zone) {
            ClimateZoneMetadata::updateOrCreate(
                ['slug' => $zone['slug']],
                $zone
            );
        }
    }
}
